spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/${DB_NAME}
    url: jdbc:postgresql://database:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    # url: jdbc:postgresql://localhost:5432/${DB_NAME}
    url: jdbc:postgresql://database:5432/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
